### ISSUE TITLE
Positioning directives

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#1]
Now Positioning directives (PD) in OASYS allow "full control" to parameters `ReferTo`, `What`, `Where`. I think this is too complicated (not all the combinations are possible for all the optical elements), and it shall be improved.

A solution is define the PD  we really need and prepare almost-locked combinations.

Some mostly used PD are:

-"Measure distance from Source" / "Set downstream of the source"
	(ReferTo = Source, What = centre, Where = centre, SameOrientation = Anye?)
	Label: "Reference Element" ---> Source.Name
	Fields: "Distance" ---> linked to Distance
	
	commonly applied to: any optical element, especially focussing mirrors
	
-"Measure distance from previous optical element" / "Set downstream"  
	(ReferTo = upstream, What = centre, Where = centre, SameOrientation = false)
	Label: "Reference Element" ---> (GetParent(self, SameOrientation=False, OnlyReference=True)).Name
	Fields: "Distance" ---> linked to Distance
	
	commonly applied to: any optical element
	Note: it refers to ANY orientation => the orientation of the optical element shall be clear in the Label field?

-"Autofocus" /"Set in the focus" 
	(ReferTo = upstream, What = centre, Where = downstream focus, SameOrientation = ?)
       Label: "Reference Element" ---> print the name of the reference focussing mirror
	Fields: "Defocus" ----> linked to Distance
	this is used for instance with detectors, 

- Others...?

**Comment by aljosahafner** [comment]
Good idea, I was just thinking about this. We should however keep the fields and buttons as universal as possible.

**Comment by capitanevs** [comment]
True, you are right.
We can insert in the possible "predefined phrases" the "Custom option" open. Depending on the selected "phrase" you have different fields. With "Custom" option you get access to the 3 fields ReferTo, What, Where. 

Any better solution is welcome.

**Comment by aljosahafner** [comment]
Located in widgets/gui/ow_wise_widget.py
 -> Function build_positioning_directive_box(self, container_box, width, element_type=ElementType.SOURCE)

**Comment by aljosahafner** [comment]
class PositioningDirectivesPhrases:

    class Type:
        Autofocus = 'Autofocus'
        DistanceFromPrevious = 'Fixed distance from previous OE'
        DistanceFromSource = 'Fixed distance from source'
        Custom = 'Custom positioning directives'

These will be the elements in the combo box. Any more?

**Comment by capitanevs** [comment]
The strings (e.g. 'Fixed distance from previous OE') are they the ones supposed to appear in the ComboBox?

I think 4 cases is all we need for the moment. We will add if need be.

**Comment by aljosahafner** [comment]
There are four cases:
![image](https://user-images.githubusercontent.com/51963146/78683595-c40e2680-78ef-11ea-98a8-a722a4efa80a.png)

The one with Autofocus has no distance:
![image](https://user-images.githubusercontent.com/51963146/78683442-9628e200-78ef-11ea-9503-c985968a7ed9.png)

Other ones have distance:
![image](https://user-images.githubusercontent.com/51963146/78683547-b5277400-78ef-11ea-878d-3954a1273d1a.png)

TODO:
For "Custom" case show What, Where and ReferTo fields.

**Comment by capitanevs** [comment]
Looks great!
- What's the difference between the two tabs? "Displacement" and "Position"? 
- Let's not forget the (read-only) field: Reference Optical element
- Let's not forget the "Defocus" field in the autofocus Phrase (equivalent to "Distance", but with defferent label).

**Comment by aljosahafner** [comment]
Displacement means SmallDisplacements. Please install Oasys and check, all the optical elements have such layout.

Yes, these are the next things to do, thanks for reminding again.

**Comment by capitanevs** [comment]
Thanks. Oasys cross checks are planned with the first all-wiser version. Most unfortunately I am out of the time for revising the current version "as is", which is the reason why I rely on you and on your reports. 

Looking at the GUI: I would remove all the non-necessary distinctions.
For instance, "Position" is clear enough. Now, I would not further add "Positioning directives" (which is code-name slang, but may be not so clear to the user). 
How about making the current substitutions?
Type => Action:
"Fixed distance from..." => "Set fixed distance from"

**Comment by aljosahafner** [comment]
Hey, this is the status and besides previous optical element, it is properly wired.

Default, fixed distance from source:
![image](https://user-images.githubusercontent.com/51963146/78785544-9be1fe80-79a7-11ea-92cf-32f536b952ce.png)

Autofocus + menu:
![image](https://user-images.githubusercontent.com/51963146/78785586-af8d6500-79a7-11ea-9318-6754beab497e.png)

Distance from previous OE:
![image](https://user-images.githubusercontent.com/51963146/78785626-c2a03500-79a7-11ea-8828-90ec09027f47.png)

Custom positioning directives:
![image](https://user-images.githubusercontent.com/51963146/78785730-f24f3d00-79a7-11ea-9a61-38b6c12d74c2.png)

**Comment by capitanevs** [comment]
Thanks for the updates.
Minor comments:
-The "custom" options should not have X and Y because they are really unusable :-). I have never used then even for debug purposes. Sorry, I did not tell you about that.
- I would add "Place" right above "at", so that the user reads "Place [centre/focus] of this O.E. at the [centre/focys/etc] of the [upstream/downstream] O.E.
- Let's always use O.E., not OE

**Comment by aljosahafner** [comment]
X, Y is for absolute positioning...

**Comment by capitanevs** [comment]
Of course, making a nice GUI **IS** cosmetics. Yes, we shall remove them. I have never happened to use them, and I have always locked the source to (0,0).

**Comment by aljosahafner** [comment]
Still to add:
* different defaults for different optical elements: absolute (X, Y = 0) for source, distance from previous o. e. for plain and elliptic mirror, autofocus for detector.

**Comment by capitanevs** [comment]
The present issue is closed.
**Done**
define the GENERAL layout of positioning directives, i.e. => OASYS standard w.r.t. WISER standard
![immagine](https://user-images.githubusercontent.com/13431660/91183195-756cf780-e6eb-11ea-8744-d5d60eb0e788.png)

**Still To do**
Improve the user experience of "smart focusing". 
"Smart focusing" behaves differently according to what elements are involved. This can be confusing.
Think of it.
