### ISSUE TITLE
Version 1.0 (beta)

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OasysWiser#14]
Features needed:

* Propagation

* Positioning

* Orientation

* Figure error

All this to be tested with a simple OWS with source, slit, plane mirror, elliptic mirror and detector of both orientations.

**Comment by capitanevs** [comment]
Just comment: the reference *.py files are in
seadrive\Examples 2020\Milestones\Test Beamline

We can create a dedicated examples\ folder on the git repository in order to improve the workflow.

**Comment by aljosahafner** [comment]
Ok, good idea, go ahead, make a folder examples/milestone_v1 or something similar

**Comment by aljosahafner** [comment]
Plus:
Issue #5 - Detector modes

**Comment by aljosahafner** [comment]
According to this, the following remains

* Detector modes: rewire the functions in Foundation to the buttons and properties

* Figure error: works, but has to be revised (?), please see figure:
![image](https://user-images.githubusercontent.com/51963146/85574865-67d9b980-b637-11ea-951b-cdb6f35ae5ed.png)

![image](https://user-images.githubusercontent.com/51963146/85574896-6e683100-b637-11ea-9ff8-fa06412aba37.png)

**Comment by aljosahafner** [comment]
Alfa/beta level reached!
