### ISSUE TITLE
Rewire the widgets

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OasysWiser#2]
Rewire:
* source
* plane mirror
* elliptical mirror
* detector

Connection path (-- means to do): OasysWiser -- WofryWiser -> LibWiser

**Comment by aljosahafner** [comment]
Oasys runs, widgets run and most of the settings are correct, however the propagation still doesn't work.
Returning the following error:
![image](https://user-images.githubusercontent.com/51963146/78914626-f738ed00-7a8a-11ea-8e8c-5a5ed4f169c3.png)

Output:
![image](https://user-images.githubusercontent.com/51963146/78914677-0ae45380-7a8b-11ea-94b2-6ed0d9254042.png)

**Comment by capitanevs** [comment]
Does it happen at the very first widget of the chain-of-responsibility or at a certain point? 
If it involves all the items, maybe have a look at the "inputs" list, and how it works with the new WiserData.

**Comment by aljosahafner** [comment]
Calculation now works. There are bugs and/or features in:

* Positioning directives - all the options have to be tested + Absolute option has to be added (together with X and Y) for the source.

* Units! - Oasys has some automatic unit handling, I have to figure out how it works.

**Comment by aljosahafner** [comment]
The last comment is now separate issues. Widgets were correctly rewired.
