### ISSUE TITLE
ALPHA - Source->apply->Error

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#23]
**Topic1**
This message must not been displayed when the user press apply onto a new source.

```
Exception                                     Traceback (most recent call last):
  File "C:\Users\Mike\Miniconda3\lib\site-packages\orangecontrib\OasysWiser\widgets\light_sources\ow_gaussian_source_1d.py", line 163, in do_wiser_beamline
    raise Exception("Nothing to apply. Source is the first element of the beamline.")
Exception: Nothing to apply. Source is the first element of the beamline.

```
**Topic2**

"apply" must initialize the LibWiser.OpticalElement. If it is not like that, then it is useless.
Expectation:
I drop an optical element A
I change its name: "A2"
I drop an optical element B
I link A to B
I click apply to B (or both A and B)
I *expect* to see that the "reference" in B has the correct name "A2".

If this is not possible, or too complicated at this level of the development, or against the logic of the chain-of-responsibility, we should give up the idea of the "apply button". And focus only to make the "compute" and "compute all" working.

We can just start with "hiding" the button without deleting the code

Comments on that?

**Comment by aljosahafner** [comment]
First thing: The three buttons are initialized in the lowest hierarchical level `WiserWidget`. Therefore, I made an error message, otherwise another solution must be found.

I'll investigate the other thing a bit and we can discuss it...

**Comment by aljosahafner** [comment]
![image](https://user-images.githubusercontent.com/51963146/91838743-45bf7180-ec4e-11ea-910f-fef72ada017f.png)
Apply button hidden, reference O. E. field also hidden.
