### ISSUE TITLE
ALPHA quick fix - gaussian source

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#24]
In the parameters of the gaussian source, we should add "M^2" (best typed with 2 as superscript).
Default value = 1
It is wired directly to M2
`def __init__(self, Lambda, Waist0, M2 = 1, XYOrigin=[0,0], AnglePropagation=0, **kwargs):`

**Comment by aljosahafner** [comment]
![image](https://user-images.githubusercontent.com/51963146/91584345-cb8fa400-e952-11ea-9e03-cbddebd0fd20.png)
