### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OasysWiser#3]
Correctly implement orientation of optical element. Probably it will be located in "Position" tab.

**Comment by capitanevs** [comment]
Totally agree on that
We can try to put it above the "Action/Type" stuff, which is a "fixed region". 
I guess you are using:
Source => Defaulted to Isotropic
and for the others we can choose between
Others => Defaulted to H ( a little bit more likely than V)
or
Others => Defaulted to Any (if we want to be more abstract).
We should choose the most self-explanatory one.

**Comment by aljosahafner** [comment]
Orientation has to be set in ow_optical_element.py -> do_wise_calculation

**Comment by aljosahafner** [comment]
![image](https://user-images.githubusercontent.com/51963146/81945747-c7878280-95fe-11ea-82f7-c70b224c173f.png)
