### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OasysWiser#4]
Multiprocessing is currently (OASYS1-WISE2) taken care of by multiprocessing package. The GUI settings are located in Calculation settings -> Parallel computing
![image](https://user-images.githubusercontent.com/51963146/78875835-ca66e480-7a4e-11ea-9373-beeebb1bea12.png)

This will go away, as the new kernel uses numba to spread over the multi CPUs and at the same time uses a JIT (just-in-time) compiler which pre-compiles code with LLVM. Even if using single-core calculation, this _should_ be faster than using native Python code with multiprocessing (this claim is untested).

**Comment by capitanevs** [comment]
Ok, get rid of that.
numba+jit is definitely faster.

**Comment by capitanevs** [comment]
I  will close the issue :-)

**Comment by aljosahafner** [comment]
Please leave these issues open. No need to comment on them, they're just placeholders here.

**Comment by aljosahafner** [comment]
In current version it is removed. Code is in ow_optical_element.py and is only commented for now.

![image](https://user-images.githubusercontent.com/51963146/78907905-a07ae580-7a81-11ea-822e-02b72050abaa.png)
