### ISSUE TITLE
Detector: Computation mode/Settings

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#5]
The detector shall allow the 3 following operations:
1) Compute the field in the nominal position (or corrected with SmallDisplacement) => Single computation. We call .ComputeField.
2) Compute the field in the best focus (not existing yet, we should call Foundation.FindFocus function)
3) Perform a scan of the field through the focus (already existing, calls Foundation.FocusSweep)

t.b.d

**Comment by aljosahafner** [comment]
I started working on this.
`Foundation.FindFocus` call will be just a placeholder right now.
`Foundation.FocusSweep` might be different now than it used to be.
![image](https://user-images.githubusercontent.com/51963146/83399175-0d1abc80-a401-11ea-8cf8-ebec4c7a3796.png)

**Comment by capitanevs** [comment]
Rename 
Focus Sweep Calculation => Through-Focus Scan
Find Focus Calculation => Find Best Focus
I would also reverse the order of the Tabs.

Add (in a fancy position, in the tab) the followin descriptions (I would try below all the commands and field etc).
(1)
Use this if you are interested in
- a complete plot of the spot size through the focal plane
- a collection of the intensity profiles
- below-average computational performance

(2)
"Use this if you are interested in
- best focus metrics (HEW, position)
- intensity profile at the best focus 
- high computational speed

Fields of (1)
"Start [mm]"
"Stop [mm]"
"Step [mm]"

to be continued

**Comment by aljosahafner** [comment]
![image](https://user-images.githubusercontent.com/51963146/90393605-5f2ebe00-e091-11ea-996e-050f90d3bcc3.png)

![image](https://user-images.githubusercontent.com/51963146/90393616-65249f00-e091-11ea-898d-322d892020bf.png)

**Comment by aljosahafner** [comment]
* Through-Focus Scan works properly

* Find Best Focus tab *must* be improved: what is the result of the FocusFind function? How is it supposed to be displayed?

**Comment by capitanevs** [comment]
**About "Find Best Focus Tab"**

Results of `FocusFind` are 
```
	Return
	--------
	Results : struct-like class
		with the following attributes

	- BestField : 1d-array (complex)
				Field at the best focus
	- BestDefocus : scalar (real)
				Defocus of the best spot
	- BestHew : scalar (real)
				Half energy width of the best spot

	- OptResult : OptimizationResult object
				Contains the results of the optimization
```

This is what I have figured out.
**Best Defocus** and  **BestHew** can be easily displayed as a string output.
-One possibility is to put them in the Left panel, like that:
![immagine](https://user-images.githubusercontent.com/13431660/91458377-be58b380-e885-11ea-8353-4663fc1dbab1.png)
If we do that, we can add the helper button which copies the BestDefocus value in the field "Central Point" of the next tab.
- If it is complicated to mix input/output, we can add a huge "Results" tab, with only these two lines...

We might use the formatting function. 

![immagine](https://user-images.githubusercontent.com/13431660/91457954-425e6b80-e885-11ea-8f87-495ce59ae237.png)

**Best Field**
It shall be displayed as Intensity, actually, not as field (so abs(E)**).
It will have its own tab, (Field Intensit, best focus is good).

Let's put the phase as well.

Nothing more (no HEW plot).

LibWiser.Units.SmartFormatter(0.0015) +'m'`

**Comment by capitanevs** [comment]
**On Through-Focus Scan**

- Here the preferred fields are (Central defocus, Half-range, N of samples) rather than (Start Stop Step).
- It seems that the overall layout is good. We need to plot:

1. The Intensity at the best focus
2. The HEW
3. The Collection of all the other intensities Intensities (which you can explore with a slider).

If this is a call
`					ResultList, HewList, SigmaList, More = lw.Foundation.FocusSweep(FocussingElement,
																	NewDefocusList,
																	DetectorSize = DetectorSize)` 
you get


**Plot2) From**
`NewDefocusList`, `HewList`
and
`NewDefocusList`, `SigmaList`

They are two ways of computing the spot size. A legend is needed:
"HEW" and "Sigma" as labels will be good.

**Plot3) From**
ResultList, which is like that
![immagine](https://user-images.githubusercontent.com/13431660/91461929-e3e7bc00-e889-11ea-8567-e72b6cd06413.png)

so 
`IntensityList = [_.Intensity for _ in ResultList]`
The title of each plot should contain the corresponding defocus value (`NewDefocusList[i]`, here) and HEW value (`HewList[i]` here)


**Plot1) **

I have just realized I do not have a function for that:-) So... let's skip Plot1 for the moment ;-)

**What else**

We may want to add some "textual output" as for the other box, but not now.

Comments?

**Comment by aljosahafner** [comment]
How to display Best Field from Find Best Focus?
Intensity is complex, do you want to show only abs(Intensity)?
Which x-axis to take?

**Comment by capitanevs** [comment]
Yes, wiser computes the fields (as they are necessary for propagation) but we always display intensity.
In certain cases I already have fillee the "intensity" attribute, as in CoreOptics.ComoutationData.
If there is not, just compute the intensity as:
Intensity is abs(field)**2
Good question about the coordinate. I will have  a look(not ad the desk now). Try to have a look at the attribhtes of the result. If there is an "S" , it s the man.





--
Inviato da myMail per Android Venerdì, 18 Settembre 2020, 09:34AM +02:00 da aljosahafner  notifications@github.com :
