### ISSUE TITLE
Advanced Computation settings/"Property Sheets"

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#6]
We have some spare flags to wire to the gui. 
- ComputationSettings.Ignore = True/False => Maybe in Computing tab?
- Else?

**Comment by aljosahafner** [comment]
Now, this option is in basic settings of the O. E.

![image](https://user-images.githubusercontent.com/51963146/81384159-8e887300-9111-11ea-9f0c-1218d724e6eb.png)
