### ISSUE TITLE
Data storage (WISEr related)

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OasysWiser#7]
I need some input to grow faster on the data storage stuff. Now I store data as 
```
lw.tl.FileIO.SaveToH5(FileOut,
						[
					  ('ParameterScan/X',XAxis),
					  ('ParameterScan/Y',YAxis),
					  ('ParameterScan/Z',ZCollection),
					  ('ParameterScan/XInfo', XInfo),
					  ('ParameterScan/YInfo', YInfo),
					  ('ParameterScan/ZInfo', ZInfo)],
					  FileAttributes,
					  Mode = 'w')
```
Each `XInfo` (which is another data strcuture, o a "Group" as it is called in hdf) looks like a good candidate for becoming "attributes" to be attached to "X", since "XInfo" is:
```
Label:  $\vartheta$
Name:   Angle
Unit:   rad
VisualizationFactor:    1000000.0
VisualizationPrefix:    u
```

I could not easily find out how to do that. If can ask someone, I can polish the data storage system.
For the moment, I only can store generic attributes (the `FileAttributes`, which is a dictionary).

**FYI**, the previous piece of code comes from
"[elettra.drive]\Examples 2020\Milestones\Test Purosangue Manipulation Script\PurosangueKernel_WiserInvestigator_00_Locked.py"

**Comment by aljosahafner** [comment]
There is documentation on how to change attributes with h5py library:
http://docs.h5py.org/en/stable/high/attr.html

For example if you create a dataset called 'example':

data_file = h5py.File('output.hdf5', 'a')
data_file.create_dataset('example', data=somedata)
# set attribute called Unit with data=1e3
data_file['example'].attrs.create('Unit', data=1e3)    

data_file.close()

**Comment by aljosahafner** [comment]
If it's still unresolved, then please reopen the issue.
